# Generated by Django 6.0.1 on 2026-03-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_rename_title_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.post')),
            ],
        ),
    ]
