# Generated by Django 6.0.1 on 2026-03-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_postnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotification',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.post'),
        ),
        migrations.AlterField(
            model_name='postnotification',
            name='authorName',
            field=models.CharField(null=True),
        ),
    ]
