# Generated by Django 6.0.1 on 2026-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_post_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='postnotification',
            name='seen',
            field=models.CharField(blank=True, choices=[('Seen', 'Seen'), ('Not Seen', 'Not Seen')], default='Not Seen', null=True),
        ),
    ]
