from urllib import response
from django.shortcuts import render
from rest_framework import generics
from rest_framework import serializers
from rest_framework import status
from rest_framework.response import Response
from .models import CustomUser
from .serializers import CustomUserSerializer
from rest_framework.decorators import api_view
