# Generated by Django 6.0.1 on 2026-02-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
