# Generated by Django 6.0.1 on 2026-02-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_wcuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WcUser',
        ),
    ]
