# Generated by Django 6.0.1 on 2026-02-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_wcuser_groups_wcuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
