# Generated by Django 6.0.1 on 2026-02-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0007_accesstoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessToken',
            new_name='RefreshToken',
        ),
    ]
