# Generated by Django 6.0.1 on 2026-02-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0008_rename_accesstoken_refreshtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefreshToken',
            new_name='WcRefreshToken',
        ),
    ]
